package client.gui;

import common.domain.Post;
import common.domain.User;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aleksander Wojcik
 */
public class PostPanel extends javax.swing.JPanel {

    private static final Logger logger = Logger.getLogger(PostPanel.class.getName());
    private MainWindow mw = null;
private java.util.ResourceBundle bundle=java.util.ResourceBundle.getBundle("Bundle");;

    public PostPanel(MainWindow mw) {
        
        this.mw = mw;
        initComponents();
    }

    public PostPanel(Post post, int number, MainWindow mw) {
        
        this.mw = mw;

        initComponents();
        try {
            User user = mw.getService().getUser(post.getAuthor_id());
            this.lbAuthor.setText(user.getLogin());
            this.lbDate.setText(post.getPost_time().toString());
            this.lbNumber.setText("#" + number);
            this.tpText.setText(post.getText());
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAuthor = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        lbDateLabel = new javax.swing.JLabel();
        lbNumber = new javax.swing.JLabel();
        sepSep1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpText = new javax.swing.JEditorPane();

        setPreferredSize(new java.awt.Dimension(450, 300));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        lbAuthor.setText(bundle.getString("autor")); // NOI18N
        lbAuthor.setName("lbAuthor"); // NOI18N

        lbDate.setText("21.10.2010 13:18");
        lbDate.setName("lbDate"); // NOI18N

        lbDateLabel.setText(bundle.getString("added")); // NOI18N
        lbDateLabel.setName("lbDateLabel"); // NOI18N

        lbNumber.setText("#1");
        lbNumber.setName("lbNumber"); // NOI18N

        sepSep1.setName("sepSep1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tpText.setEditable(false);
        tpText.setName("tpText"); // NOI18N
        jScrollPane1.setViewportView(tpText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepSep1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(lbDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sepSep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumber)
                    .addComponent(lbAuthor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDateLabel)
                    .addComponent(lbDate))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAuthor;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDateLabel;
    private javax.swing.JLabel lbNumber;
    private javax.swing.JSeparator sepSep1;
    private javax.swing.JEditorPane tpText;
    // End of variables declaration//GEN-END:variables
}
